### ISSUE TITLE
Better way display network image

### ISSUE THREAD

**Issue by ltype** [NyaaPantsu/NyaaPantsu-android-app#37]
>07-15 09:43:59.919 30023-30023/cat.pantsu.nyaapantsu E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: cat.pantsu.nyaapantsu, PID: 30023
                                                                       java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter bitmap
                                                                           at cat.pantsu.nyaapantsu.helper.ImageGetterAsyncTask.onPostExecute(ImageGetter.kt:0)
                                                                           at cat.pantsu.nyaapantsu.helper.ImageGetterAsyncTask.onPostExecute(ImageGetter.kt:22)
                                                                           at android.os.AsyncTask.finish(AsyncTask.java:667)
                                                                           at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                           at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

Should we use [Fresco](https://github.com/facebook/fresco) for display network image?

**Comment by xdk78** [comment]
We use Glide, it's very good, so maybe we should use Rx Kotlin Instead async task?

**Comment by xdk78** [comment]
Ok, if this working better I trust you
